"""ClassRepository — abstract interface"""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from app.domain.class_.aggregate import Class, ClassMembership


@runtime_checkable
class ClassRepository(Protocol):
    def find_by_id(self, class_id: str) -> Class | None: ...

    def find_by_join_code(self, code: str) -> Class | None: ...

    def find_by_teacher(self, teacher_id: str) -> list[Class]: ...

    def find_all(self) -> list[Class]: ...

    def save(self, cls_: Class) -> None: ...

    def delete(self, class_id: str) -> None: ...

    def find_membership(self, class_id: str, student_id: str) -> ClassMembership | None: ...

    def find_memberships_by_class(self, class_id: str) -> list[ClassMembership]: ...

    def find_memberships_by_student(self, student_id: str) -> list[ClassMembership]: ...

    def save_membership(self, membership: ClassMembership) -> None: ...

    def delete_membership(self, class_id: str, student_id: str) -> None: ...
