"""Fix dropped tables

Revision ID: 58cbdc857a81
Revises: m7b8c9d0e1f2
Create Date: 2026-05-02 05:08:09.692425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58cbdc857a81'
down_revision: Union[str, None] = 'm7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talent_allocations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('talent_node_id', sa.String(length=100), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_level >= 1', name='ck_talent_level_min'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'talent_node_id', name='uq_user_talent_node')
    )
    op.create_index('ix_talent_allocation_user_id', 'talent_allocations', ['user_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('achievement_id', sa.String(length=100), nullable=False),
    sa.Column('talent_points', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_index('ix_user_achievement_user_id', 'user_achievements', ['user_id'], unique=False)
    op.create_table('removed_class_memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'student_id', name='uq_removed_memberships_class_student')
    )
    op.create_index('ix_removed_memberships_student_id', 'removed_class_memberships', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_removed_memberships_student_id', table_name='removed_class_memberships')
    op.drop_table('removed_class_memberships')
    op.drop_index('ix_user_achievement_user_id', table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index('ix_talent_allocation_user_id', table_name='talent_allocations')
    op.drop_table('talent_allocations')
    # ### end Alembic commands ###
