"""Initial schema

Revision ID: aec17830bec5
Revises: 
Create Date: 2026-04-14 06:11:53.275344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec17830bec5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='sessionstatus'), nullable=False),
    sa.Column('current_wave', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('level BETWEEN 1 AND 4', name='ck_game_session_level_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_session_user_id', 'game_sessions', ['user_id'], unique=False)
    op.create_index('uq_one_active_per_user', 'game_sessions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('waves_survived', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('level BETWEEN 1 AND 4', name='ck_leaderboard_level_range'),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', name='uq_leaderboard_session_id')
    )
    op.create_index('ix_leaderboard_level_score', 'leaderboard_entries', ['level', 'score'], unique=False)
    op.create_index('ix_leaderboard_user_id', 'leaderboard_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leaderboard_user_id', table_name='leaderboard_entries')
    op.drop_index('ix_leaderboard_level_score', table_name='leaderboard_entries')
    op.drop_table('leaderboard_entries')
    op.drop_index('uq_one_active_per_user', table_name='game_sessions', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_game_session_user_id', table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
