"""TerritoryRepository — abstract interface"""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from app.domain.territory.aggregate import (
    GrabbingTerritoryActivity,
    TerritorySlot,
    TerritoryOccupation,
)


@runtime_checkable
class TerritoryRepository(Protocol):

    def find_activity_by_id(self, activity_id: str) -> GrabbingTerritoryActivity | None: ...

    def find_activities_by_class(self, class_id: str) -> list[GrabbingTerritoryActivity]: ...

    def find_activities_by_teacher(self, teacher_id: str) -> list[GrabbingTerritoryActivity]: ...

    def find_all_activities(self) -> list[GrabbingTerritoryActivity]: ...

    def find_unsettled_expired_activities(self) -> list[GrabbingTerritoryActivity]: ...

    def save_activity(self, activity: GrabbingTerritoryActivity) -> None: ...

    def find_slot_by_id(self, slot_id: str) -> TerritorySlot | None: ...

    def find_slots_by_activity(self, activity_id: str) -> list[TerritorySlot]: ...

    def save_slot(self, slot: TerritorySlot) -> None: ...

    def find_occupation_by_slot_for_update(self, slot_id: str) -> TerritoryOccupation | None: ...

    def count_occupations_by_student(self, activity_id: str, student_id: str) -> int: ...

    def count_occupations_by_student_for_update(self, activity_id: str, student_id: str) -> int: ...

    def is_session_used(self, session_id: str) -> bool: ...

    def save_occupation(self, occupation: TerritoryOccupation) -> None: ...

    def delete_occupation(self, slot_id: str) -> None: ...

    def find_occupations_by_activity(self, activity_id: str) -> list[TerritoryOccupation]: ...

    def count_territories_by_student(self, student_id: str) -> int: ...

    def find_max_star_for_student(self, student_id: str) -> int: ...

    def get_external_rankings(self, activity_id: str) -> list[dict]: ...
